### PR TITLE
Update DG Use Case

### PR DESCRIPTION
**Pull request by bgopi23**
Resolves https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/42

### CODE REVIEW

**Comment by jjchee77** [comment]
Might want to follow the following structure for each use case:

- System
- Use case
- Actor
- MSS
- Extensions

For some use cases, some sections are currently missing.
Eg, UC01, **Actor** section is missing. UC03, **System** section is missing.

Other than that, LGTM!

**Comment by bgopi23** [comment]
@jjchee77 thanks, fixed

**Comment by jjchee77** [comment]
Might wanna add horizontal lines to separate each use case for better readability.
Sorry for not pointing out that earlier!

I think `<br/>` works.

**Comment by jjchee77** [comment]
LGTM!

**Review by jjchee77 — APPROVED** [review]
LGTM!

**Pull request merged**
