### PR TITLE
Feature: Add weight feature with history tracking, and height feature

### LINKED ISSUE #158: Feature: Save client weight with date
As a user, I want to log a client's weight on a particular date, so that I can have a metric to monitor the client's progress.

### PR DESCRIPTION
**Pull request by ruijietay**
As part of v1.3b, users can now track the height and weights of clients.

The weight values are associated with a date, and previous weight values can also be tracked for each client.

Resolves #158.

### CODE REVIEW

**Comment by bgopi23** [comment]
wow

**Comment by dillontkh** [comment]
Found some bugs:

image

1. Incorrect response message when trying to remove a weight from a client with no more weights saved.


https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/67903d2a-902c-4a57-a484-c69426377e19

2. When trying to view the details of a person with no weight stored, the updating of the detail pane stops at the weight, causing any information after that (height, note, qrcode) to not be updated.

**Comment by ruijietay** [comment]
> Found some bugs:
> 
> image
> 
>     1. Incorrect response message when trying to remove a weight from a client with no more weights saved.
> 
> 
> bug.mp4
> 
>     2. When trying to view the details of a person with no weight stored, the updating of the detail pane stops at the weight, causing any information after that (height, note, qrcode) to not be updated.

Thank you for pointing these out! I've fixed it accordingly.

**Comment by bgopi23** [comment]
1 bug i found

image
it allows me to input negative weights @ruijietay

**Comment by bgopi23** [comment]
some bugs i found

image
index is specifed but error message says no index

<hr>

image
the date is showing T17 or something for me

**Comment by ruijietay** [comment]
> some bugs i found
> 
> image index is specifed but error message says no index
> 
> image the date is showing T20 or something for me

Thanks for pointing that out! I think the `T20...` portion refers to the time. Better formatting of the date and time could be used, maybe it would be better to create an issue for that?

As for the error messages, I've fixed that. Thank you!

**Review by dillontkh — APPROVED** [review]
Wow, must've been a lot of work. Good job!

LGTM!

**Review by RyanNgWH — APPROVED** [review]
Amazing work! LGTM!

**Pull request merged**
