### PR TITLE
Docs - Add captions

### PR DESCRIPTION
**Pull request by bgopi23**

### CODE REVIEW

**Review by jjchee77 — APPROVED** [review]
LGTM!

**Review by dillontkh — CHANGES_REQUESTED** [review]
image

The numbering gets reset by the picture. I think we have to indent the `<figure>` tags

**Comment by dillontkh** [comment]
> image
> 
> The numbering gets reset by the picture. I think we have to indent the `<figure>` tags

just pushed a fix for this

**Review by dillontkh — APPROVED** [review]
LGTM!

**Review by RyanNgWH — APPROVED** [review]
LGTM

**Pull request merged**
