### PR TITLE
Enhancement: Improved how results are displayed

### PR DESCRIPTION
**Pull request by bgopi23**
Resolves https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/139 and https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/139#issuecomment-2011488211
<hr>

Before (1):
image
After (1):
image
<hr>

Before (2): 
image
After (2):
image

### CODE REVIEW

**Comment by RyanNgWH** [comment]
Would it be better to have each attribute on a new line? 
E.g
```
Client successfully added!
Name: John
Phone: 99999999
```

**Comment by bgopi23** [comment]
So we just display the name and number?

**Review by dillontkh — APPROVED** [review]
LGTM!

**Review by ruijietay — COMMENTED** [review]
Great work formatting the output! However, it seems like the output area is still scrollable for really long inputs like the screenshot below. Should this be the case?

image

I also noticed that there are certain files like `NameContainsKeywordsPredicate.java` and `NameContainsKeywordsPredicateTest.java` present in the branch that I pulled for this PR. Should these be there? (Since we have previously merged a PR to remove these redundant files from master #130).

But other than that, if we are not accounting for edge cases such as those really long names and notes shown above, I think its good to merge!

**Comment by bgopi23** [comment]
@ruijietay horizontal scrollability if its too long is fine but it shouldnt be vertically scrollable. Is it vertically scrollable for u?

**Review by ruijietay — APPROVED** [review]
LGTM!  🍾

**Pull request merged**
