### PR TITLE
Bug: Fix result messages

### PR DESCRIPTION
**Pull request by bgopi23**
Resolves: https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/188

### CODE REVIEW

**Review by RyanNgWH — COMMENTED** [review]
Great work! Should we add the following test cases as well (under `ListCommandTest`)?
1. No clients to list
2. One client listed

**Comment by bgopi23** [comment]
@RyanNgWH good idea, ive added them

**Review by RyanNgWH — APPROVED** [review]
LGTM!

**Review by dillontkh — APPROVED** [review]
LGTM!

**Pull request merged**
