### PR TITLE
Docs: Update Developer Guide

### PR DESCRIPTION
**Pull request by dillontkh**
Main Changes:

* Remove leftover placeholder text from AB3
* Update Ui and Model class diagrams to better reflect our current app
* Update outdated examples

An issue I identified was the text of some of the larger UML diagrams were much smaller than the page text, which could be considered a DG bug. 

However, I am not sure how to fix it apart from breaking the diagram down into multiple smaller sections.  Any suggestions are welcome.

e.g.
image

### CODE REVIEW

**Comment by ruijietay** [comment]
Maybe we could shorten the length of the parameter names and replace them with "..." where needed?

**Review by ruijietay — APPROVED** [review]
LGTM

**Review by RyanNgWH — APPROVED** [review]
LGTM!

**Review by bgopi23 — APPROVED** [review]
LGTM!

**Pull request merged**
